login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

e_commerce:
    resource: "@ECommerceBundle/Resources/config/routing.yml"
    prefix:   /
